version: "3.9"
services:
  geth:
    container_name: geth
    image: contractfuzzer/geth
    build:
      context: .
      dockerfile: Dockerfile.geth
    ports:
      - "8545:8545"
    environment:
      - FUZZER_HOST=host.docker.internal
      - FUZZER_PORT=8889
      # - FUZZER_HOST=172.17.196.146
  tester:
    container_name: tester
    image: contractfuzzer/tester
    build:
      context: .
      dockerfile: Dockerfile.tester
    ports:
      - "8088:8088"
    depends_on:
      - "geth"
    environment:
      - GETH_HOST=geth
      - FUZZER_HOST=host.docker.internal
      - FUZZER_PORT=8889
  # fuzzer:
  #   container_name: fuzzer
  #   image: contractfuzzer/fuzzer
  #   build:
  #     context: ./contractfuzzer
  #   ports:
  #     - "8888:8888"
  #   depends_on:
  #     - "tester"
  #   environment:
  #     - TESTER_HOST=tester
  #   volumes:
  #     - ./examples:/exec_env/examples
  # benchmark:
  #   container_name: benchmark
  #   image: contractfuzzer/benchmark
  #   build:
  #     context: ./benchmark
  #   ports:
  #     - "8888:8888"
  #   depends_on:
  #     - "fuzzer"
  #   environment:
  #     - TESTER_HOST=tester
  #   volumes:
  #     - ./examples:/exec_env/examples
  #     - ".:/exec_env/output"
